Miscellaneous Settings PRIM-266
Affordability4You/QA_Automation pull request #13
Opened 2021-09-02 08:35 UTC by JPPrimus123

2021-09-02 13:55 UTC, ahaynes91 requested changes
Need to add a validation step that checks for the component's existence.

2021-09-02 13:55 UTC, ahaynes91 commented on PageObjects/BankSettingPageObject.cs
> +        }
This is selecting the application but where is the validation that the DTI threshold component exists (or doesn't exist) on the SBO?

2021-09-02 16:06 UTC, ahaynes91 requested changes

2021-09-02 16:06 UTC, ahaynes91 commented on PageObjects/BankSettingPageObject.cs
> +        }
What I am asking for is after clicking to open the application, verify on the Solution Based Outcome tab the DTI Threshold component's existence.

2021-09-03 12:49 UTC, ahaynes91 approved these changes

2021-09-03 12:59 UTC, JPPrimus123 commented
hi Alex,

Thanks

Regards
Jay Prakash
________________________________
From: ahaynes91 ***@***.***>
Sent: 03 September 2021 18:19
To: Affordability4You/QA_Automation ***@***.***>
Cc: Jay Pathak ***@***.***>; Assign ***@***.***>
Subject: Re: [Affordability4You/QA_Automation] Miscellaneous Settings PRIM-266 (#13)


[EXTERNAL]

@ahaynes91 approved this pull request.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAffordability4You%2FQA_Automation%2Fpull%2F13%23pullrequestreview-746069031&data=04%7C01%7Cjai.pathak%40affordit.com%7C8dc99dcc90a3455461dd08d96ed93b03%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637662701544542481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hh35fy5SUqbQl51tezDyaHxD8QzaqdxF7cCtME68%2BYM%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU3XDQBBZTRWDWVTDHJ7FVTUAC74RANCNFSM5DIQ54EQ&data=04%7C01%7Cjai.pathak%40affordit.com%7C8dc99dcc90a3455461dd08d96ed93b03%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637662701544552438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oXkIhhhxZXuRJ5Rg1yZo1EAXzCt2or6EM2o0OQL1ZZQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjai.pathak%40affordit.com%7C8dc99dcc90a3455461dd08d96ed93b03%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637662701544552438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dXfstwwEUo1jO2xumoPEfHojlKv7IzlI3j5Pw%2BKi3Jk%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjai.pathak%40affordit.com%7C8dc99dcc90a3455461dd08d96ed93b03%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637662701544562391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XbNIVHRdpTJBQ84GU7vCS27qy5%2BsLyKFcP54QjBJ9u4%3D&reserved=0>.

2021-09-03 13:00 UTC, merged