PRIM-192 Bank Setting ( All Sub Modules)
Affordability4You/QA_Automation pull request #5
Opened 2021-08-19 14:03 UTC by JPPrimus123

Bank Setting - All the modules are Completed. Please Review it.

2021-08-19 15:37 UTC, ahaynes91 requested changes

2021-08-19 15:37 UTC, ahaynes91 commented on PageObjects/BankSettingPageObject.cs
> +            string path = @"C:\Users\ROSHAN\OneDrive - Primus Software Corporation\Desktop\title-logo.png";
Wouldn't this cause an error if someone else ran the test?

2021-08-19 15:37 UTC, ahaynes91 commented on Tests/FeatureFiles/BankSetting.feature
> +	When Click on Hamberber Menu
Hamburger

2021-08-19 15:37 UTC, ahaynes91 commented on Tests/Steps/BankSetting.cs
> +            _bSPageObject.SelectPurpose();
Please rename if this is hardcoded to select "Logo" from the dropdown.

2021-08-19 15:40 UTC, JPPrimus123 commented on PageObjects/BankSettingPageObject.cs
> +            string path = @"C:\Users\ROSHAN\OneDrive - Primus Software Corporation\Desktop\title-logo.png";
for that we have to change the path of the file. it will not throw an error, actually you won't be able to add the file

2021-08-19 15:40 UTC, JPPrimus123 commented on Tests/Steps/BankSetting.cs
> +            _bSPageObject.SelectPurpose();
no it is not

2021-08-19 15:49 UTC, JPPrimus123 commented
Hi Alex,

I did all changes which you have suggested, Pls check this
https://github.com/Affordability4You/QA_Automation/pull/5/commits/1e937d5f5120e342e1f0c1e87db1b7cf4b2939d4

Regards
Jay Prakash
________________________________
From: ahaynes91 ***@***.***>
Sent: 19 August 2021 21:07
To: Affordability4You/QA_Automation ***@***.***>
Cc: Jay Pathak ***@***.***>; Assign ***@***.***>
Subject: Re: [Affordability4You/QA_Automation] PRIM-192 Bank Setting ( All Sub Modules) (#5)


[EXTERNAL]

@ahaynes91 requested changes on this pull request.

________________________________

In PageObjects/BankSettingPageObject.cs<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAffordability4You%2FQA_Automation%2Fpull%2F5%23discussion_r692220981&data=04%7C01%7Cjai.pathak%40affordit.com%7C69b60b7ac18a453f9e5008d963273739%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649842379265862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r0asIW1nbgNxgGYm3rp%2FZL%2BUCVM3oVEBRyE3038X%2F7I%3D&reserved=0>:

> +        }

+        public void UploadButton()

+        {

+            Click(Uploadbtn);

+        }

+        public void ClickOnDropDown()

+        {

+            Click(purpose);

+        }

+        public void SelectPurpose()

+        {

+            Click(logo);

+        }

+        public void UploadFile()

+        {

+            string path = @"C:\Users\ROSHAN\OneDrive - Primus Software Corporation\Desktop\title-logo.png";



Wouldn't this cause an error if someone else ran the test?

________________________________

In Tests/FeatureFiles/BankSetting.feature<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAffordability4You%2FQA_Automation%2Fpull%2F5%23discussion_r692226827&data=04%7C01%7Cjai.pathak%40affordit.com%7C69b60b7ac18a453f9e5008d963273739%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649842379275819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jX2jZOY8gTaIa22NZwXkBWfhYegKhrJ5%2F6WYYOmbc5k%3D&reserved=0>:

> @@ -0,0 +1,94 @@

+﻿Feature: PRIM-192 As a user I should be able to modify the Bank Settings

+Scenario: Scenario_01_Bank Rates PRIM-219

+       Given Navigate to New Application Page with "CorrectUsername" and "CorrectPassword"

+       And Select "Meridian Test (MER)" tenent

+       When Click on Hamberber Menu



Hamburger

________________________________

In Tests/Steps/BankSetting.cs<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAffordability4You%2FQA_Automation%2Fpull%2F5%23discussion_r692238588&data=04%7C01%7Cjai.pathak%40affordit.com%7C69b60b7ac18a453f9e5008d963273739%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649842379275819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WZ80vMaIXs9c3bJQpd3tESFIWmRUOUpw6FDQKSLfuHo%3D&reserved=0>:

> +            _bSPageObject.TenantFiles();

+        }

+        [Then(@"Click on Upload button")]

+        public void ThenClickOnUploadButton()

+        {

+            _bSPageObject.UploadButton();

+        }

+        [Then(@"Choose on Purpose from Dropdown")]

+        public void ThenChooseOnPurposeFromDropdown()

+        {

+            _bSPageObject.ClickOnDropDown();

+        }

+        [Then(@"Select Logo from dropdown")]

+        public void ThenSelectLogoFromDropdown()

+        {

+            _bSPageObject.SelectPurpose();



Please rename if this is hardcoded to select "Logo" from the dropdown.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAffordability4You%2FQA_Automation%2Fpull%2F5%23pullrequestreview-734152658&data=04%7C01%7Cjai.pathak%40affordit.com%7C69b60b7ac18a453f9e5008d963273739%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649842379285780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Kzg133enmODImiSheFBStCjFef3tSp8BK84l8wmYXA4%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU3XDQGJKNDVXFEXNKVEZ3LT5UQKRANCNFSM5COJQADA&data=04%7C01%7Cjai.pathak%40affordit.com%7C69b60b7ac18a453f9e5008d963273739%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649842379285780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9kx5D%2F1aIlsc3vY%2FbZBwicMgGChpw2HUebuTraKIhG0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjai.pathak%40affordit.com%7C69b60b7ac18a453f9e5008d963273739%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649842379285780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ovxWSFW9ciKCoUZNHSnKP27O8CfjH%2BB%2FVw9p9ur8V7o%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjai.pathak%40affordit.com%7C69b60b7ac18a453f9e5008d963273739%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649842379295743%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RZh%2FBE7LLr7fInTpbbcrmEJJM%2B84UygZ40o7d6ayXTA%3D&reserved=0>.

2021-08-19 16:16 UTC, ahaynes91 commented on Tests/Steps/BankSetting.cs
> +            _bSPageObject.SelectPurpose();
Then how is "Logo" being selected? What if I wanted to select "Disclosure" instead?

2021-08-19 16:23 UTC, JPPrimus123 commented
Hi Alex,
 Now I have change Logo https://github.com/Affordability4You/QA_Automation/pull/5/commits/1e683bb3be79f02bf220a615d04ff95493fea35a
[https://avatars.githubusercontent.com/u/87519680?s=400&v=4]<https://github.com/Affordability4You/QA_Automation/pull/5/commits/1e683bb3be79f02bf220a615d04ff95493fea35a>
PRIM-192 Bank Setting ( All Sub Modules) by JPPrimus123 · Pull Request #5 · Affordability4You/QA_Automation<https://github.com/Affordability4You/QA_Automation/pull/5/commits/1e683bb3be79f02bf220a615d04ff95493fea35a>
Bank Setting - All the modules are Completed. Please Review it.
github.com

Regards
Jay Prakash
________________________________
From: ahaynes91 ***@***.***>
Sent: 19 August 2021 21:46
To: Affordability4You/QA_Automation ***@***.***>
Cc: Jay Pathak ***@***.***>; Assign ***@***.***>
Subject: Re: [Affordability4You/QA_Automation] PRIM-192 Bank Setting ( All Sub Modules) (#5)


[EXTERNAL]

@ahaynes91 commented on this pull request.

________________________________

In Tests/Steps/BankSetting.cs<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAffordability4You%2FQA_Automation%2Fpull%2F5%23discussion_r692282014&data=04%7C01%7Cjai.pathak%40affordit.com%7C99f0db2c38e14c091f6f08d9632cad84%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649865810818947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FZ36osfDpDOfjXuKIbkxnDEfabIKudCmm66POv8Lswk%3D&reserved=0>:

> +            _bSPageObject.TenantFiles();
+        }
+        [Then(@"Click on Upload button")]
+        public void ThenClickOnUploadButton()
+        {
+            _bSPageObject.UploadButton();
+        }
+        [Then(@"Choose on Purpose from Dropdown")]
+        public void ThenChooseOnPurposeFromDropdown()
+        {
+            _bSPageObject.ClickOnDropDown();
+        }
+        [Then(@"Select Logo from dropdown")]
+        public void ThenSelectLogoFromDropdown()
+        {
+            _bSPageObject.SelectPurpose();


Then how is "Logo" being selected? What if I wanted to select "Disclosure" instead?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAffordability4You%2FQA_Automation%2Fpull%2F5%23discussion_r692282014&data=04%7C01%7Cjai.pathak%40affordit.com%7C99f0db2c38e14c091f6f08d9632cad84%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649865810818947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FZ36osfDpDOfjXuKIbkxnDEfabIKudCmm66POv8Lswk%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU3XDQFOGWWQMRZPP6KHVDLT5UU5FANCNFSM5COJQADA&data=04%7C01%7Cjai.pathak%40affordit.com%7C99f0db2c38e14c091f6f08d9632cad84%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649865810828903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rXrWyOEvos61%2BAP%2FoFXxeTdE2SKNcuqyI%2FcipeWPMlM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjai.pathak%40affordit.com%7C99f0db2c38e14c091f6f08d9632cad84%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649865810828903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UpYxGsXCle%2FYlQU20WvEw3PINuFNt7oWHGYVtZqy1nc%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjai.pathak%40affordit.com%7C99f0db2c38e14c091f6f08d9632cad84%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649865810838871%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FDgtBdk5F%2BARLNx35f9rVpJe3A5%2B8uOiKX7rPeaP9a0%3D&reserved=0>.

2021-08-19 19:11 UTC, ahaynes91 commented
I pulled down the branch as I was curious about the `AutoItX3` class and immediately got the following errors:
- The type or namespace name 'AutoItX3Lib' could not be found (are you missing a using directive or an assembly reference?)
- The type or namespace name 'AutoItX3' could not be found (are you missing a using directive or an assembly reference?)

How can this be resolved so no one else would run into this issue?

2021-08-20 07:01 UTC, JPPrimus123 commented
Hi Alex,
you have to add his class in your app. I push the code when it works properly
Regards

Jay Prakash

________________________________
From: ahaynes91 ***@***.***>
Sent: 20 August 2021 00:42
To: Affordability4You/QA_Automation ***@***.***>
Cc: Jay Pathak ***@***.***>; Assign ***@***.***>
Subject: Re: [Affordability4You/QA_Automation] PRIM-192 Bank Setting ( All Sub Modules) (#5)


[EXTERNAL]

I pulled down the branch as I was curious about the AutoItX3 class and immediately got the following errors:

  *   The type or namespace name 'AutoItX3Lib' could not be found (are you missing a using directive or an assembly reference?)
  *   The type or namespace name 'AutoItX3' could not be found (are you missing a using directive or an assembly reference?)

How can this be resolved so no one else would run into this issue?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAffordability4You%2FQA_Automation%2Fpull%2F5%23issuecomment-902171721&data=04%7C01%7Cjai.pathak%40affordit.com%7C814dce7aacda48958d3a08d963453c05%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649971318668966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D74c5%2BTMKiiBeA9pPV7hZJzddh03t1H4X4JczxK88bo%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU3XDQBA66LK26ZDD7DIIO3T5VJQLANCNFSM5COJQADA&data=04%7C01%7Cjai.pathak%40affordit.com%7C814dce7aacda48958d3a08d963453c05%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649971318678917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cgh6G2bS%2BPM94jZvsyi6u%2BAKneQy0rK%2FiSuvQ3otF%2BE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjai.pathak%40affordit.com%7C814dce7aacda48958d3a08d963453c05%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649971318678917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=B%2BVJqywncc%2FyJkHENbfzDeZe3bJeZOV%2FFMeLoNqh2HM%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjai.pathak%40affordit.com%7C814dce7aacda48958d3a08d963453c05%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637649971318678917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TvWJ002yAPPkYMsd6mJdFwgN5m2pIIlhVDs0wlzL5qs%3D&reserved=0>.

2021-08-20 15:51 UTC, ahaynes91 commented
i just realized this is a COM reference which means I will need to register the DLL on my machine, and going forward, everyone else's machine, in order to make this work. Is there a reason why this way is chosen instead of reference a NuGet package (if there is one)?

2021-08-20 15:53 UTC, JPPrimus123 commented
yes alex
________________________________
From: ahaynes91 ***@***.***>
Sent: 20 August 2021 21:21
To: Affordability4You/QA_Automation ***@***.***>
Cc: Jay Pathak ***@***.***>; Assign ***@***.***>
Subject: Re: [Affordability4You/QA_Automation] PRIM-192 Bank Setting ( All Sub Modules) (#5)


[EXTERNAL]

i just realized this is a COM reference which means I will need to register the DLL on my machine, and going forward, everyone else's machine, in order to make this work. Is there a reason why this way is chosen instead of reference a NuGet package (if there is one)?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAffordability4You%2FQA_Automation%2Fpull%2F5%23issuecomment-902789075&data=04%7C01%7Cjai.pathak%40affordit.com%7C8cf08cf31e37441e656808d963f25c88%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637650714862738976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PvWHVHsvdSs0%2BdDmMhDYzsZ2t%2B8zO9r3a8z1jgqtqWs%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU3XDQE427ERHI3IMPRAJ7LT5Z2XVANCNFSM5COJQADA&data=04%7C01%7Cjai.pathak%40affordit.com%7C8cf08cf31e37441e656808d963f25c88%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637650714862748930%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OHuKUPmovPxvEFvX5zgOgORWH9CKt7E6TyHm11PbIsc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjai.pathak%40affordit.com%7C8cf08cf31e37441e656808d963f25c88%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637650714862748930%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ARhW%2FDz%2B%2BZFvkwYLnK343ba2KfvI%2Br4pkoJ0bCw3P9k%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjai.pathak%40affordit.com%7C8cf08cf31e37441e656808d963f25c88%7Cec42a23833a746c7b8f671b69f75bd37%7C0%7C0%7C637650714862758888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WelGZX%2F4fa2KN6kv8axSXCtLO1%2FJP00lpSbNciCY2FQ%3D&reserved=0>.

2021-08-25 13:31 UTC, ahaynes91 commented
Closing. Issues resolved in https://github.com/Affordability4You/QA_Automation/pull/9

2021-08-25 13:31 UTC, closed without merging