PRIM-240SecuritySettings(All Subtasks)
Affordability4You/QA_Automation pull request #6
Opened 2021-08-19 14:31 UTC by bhatt7821

PRIM-240SecuritySettings(All Subtasks)

2021-08-19 15:49 UTC, ahaynes91 requested changes
Small changes suggested

2021-08-19 15:49 UTC, ahaynes91 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +        // protected string loggedUser;
Remove please

2021-08-19 15:49 UTC, ahaynes91 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +            act = new Actions(driver);
_driver

2021-08-19 16:21 UTC, bhatt7821 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +        // protected string loggedUser;
ok

2021-08-19 16:21 UTC, bhatt7821 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +            act = new Actions(driver);
_driver is an object of IWebDriver

2021-08-23 17:53 UTC, ahaynes91 commented
Changes were included in https://github.com/Affordability4You/QA_Automation/pull/8

2021-08-23 17:53 UTC, closed without merging