PRIM-241AuditRecords
Affordability4You/QA_Automation pull request #7
Opened 2021-08-19 14:53 UTC by bhatt7821

PRIM-241AuditRecords

2021-08-19 15:56 UTC, ahaynes91 requested changes

2021-08-19 15:56 UTC, ahaynes91 commented on Tests/FeatureFiles/View_Search_Audit_Records.feature
> +#	Then Enter Occurred On in Search box and Click Enter
If these scenarios aren't necessary please remove

2021-08-19 15:56 UTC, ahaynes91 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +        // protected string loggedUser;
Please remove

2021-08-19 15:56 UTC, ahaynes91 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +            act = new Actions(driver);
_driver

2021-08-19 15:56 UTC, ahaynes91 commented on Tests/Steps/View_Search_Audit_Records.cs
> +        // protected string loggedUser;
Please remove

2021-08-19 15:56 UTC, ahaynes91 commented on Tests/Steps/View_Search_Audit_Records.cs
> +            act = new Actions(driver);
_driver

2021-08-19 16:34 UTC, bhatt7821 commented on Tests/FeatureFiles/View_Search_Audit_Records.feature
> +#	Then Enter Occurred On in Search box and Click Enter
These are the Scenarios for Search Audit Records, I have also made the script for these scenarios.
Once bugs of Searching audit records get fixed we can remove these comments.

2021-08-19 16:34 UTC, bhatt7821 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +        // protected string loggedUser;
Done

2021-08-19 16:34 UTC, bhatt7821 commented on Tests/Steps/View_Search_Audit_Records.cs
> +        // protected string loggedUser;
ok

2021-08-19 16:35 UTC, bhatt7821 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +            act = new Actions(driver);
_driver is an object of IWebDriver

2021-08-19 16:35 UTC, bhatt7821 commented on Tests/Steps/View_Search_Audit_Records.cs
> +            act = new Actions(driver);
_driver is an object of IWebDriver

2021-08-19 18:37 UTC, ahaynes91 commented on Tests/FeatureFiles/View_Search_Audit_Records.feature
> +#	Then Enter Occurred On in Search box and Click Enter
Understood. Just letting you know a bug ticket has been made to fix it but it hasn't been added to any future sprints yet.

2021-08-19 18:45 UTC, ahaynes91 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +            act = new Actions(driver);
I'm aware. I was just curious why use this object versus the private one?

2021-08-20 12:53 UTC, bhatt7821 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +            act = new Actions(driver);
I took this as private because This is used with in a class.

2021-08-20 12:55 UTC, bhatt7821 commented on Tests/FeatureFiles/View_Search_Audit_Records.feature
> +#	Then Enter Occurred On in Search box and Click Enter
Ok, I am removing it.

2021-08-23 17:53 UTC, ahaynes91 commented
Changes were included in https://github.com/Affordability4You/QA_Automation/pull/8

2021-08-23 17:53 UTC, closed without merging