PRIM-242BillingandInvoice
Affordability4You/QA_Automation pull request #8
Opened 2021-08-19 15:06 UTC by bhatt7821

PRIM-242BillingandInvoice

2021-08-19 16:04 UTC, ahaynes91 requested changes

2021-08-19 16:04 UTC, ahaynes91 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +﻿using Affordit_Automation.PageObjects;
First comment applies to this file as well.

2021-08-19 16:04 UTC, ahaynes91 commented on Tests/Steps/BillingAndInvoiceStepDefinition.cs
> +        // protected string loggedUser;
Please remove

2021-08-19 16:04 UTC, ahaynes91 commented on Tests/Steps/BillingAndInvoiceStepDefinition.cs
> +            act = new Actions(driver);
_driver

2021-08-19 16:23 UTC, bhatt7821 commented on PageObjects/Add_Edit_Tenant_User_PageObjects.cs
> +﻿using Affordit_Automation.Utils;
ok

2021-08-19 16:23 UTC, bhatt7821 commented on Tests/Steps/Add_Edit_Tenant_User_StepDefination.cs
> +﻿using Affordit_Automation.PageObjects;
ok

2021-08-19 16:23 UTC, bhatt7821 commented on Tests/Steps/BillingAndInvoiceStepDefinition.cs
> +        // protected string loggedUser;
ok

2021-08-19 16:24 UTC, bhatt7821 commented on Tests/Steps/BillingAndInvoiceStepDefinition.cs
> +            act = new Actions(driver);
_driver is an object of IWebDriver

2021-08-20 15:44 UTC, ahaynes91 approved these changes

2021-08-23 18:44 UTC, merged